language: go

go:
  - "1.14.x"
  - "1.13.x"

go_import_path: github.com/feiquan123/rotat-logger

env:
  global:
    - GO111MODULE=on
    - HOME=$TRAVIS_HOME
  matrix:
    - OS_TYPE=centos OS_VERSION=7

before_script:
  - cd ${TRAVIS_HOME}
  - ls

script:
  - cd ${GOPATH}/src/github.com/feiquan123/rotat-logger
  - go fmt ./... && [[ -z `git status -s` ]]
  - go mod vendor && go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
